schemaVersion: 2.1.0
metadata:
  name: kubernetes-image-version-checker
components:
  - name: kubernetes-image-version-checker
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      env:
        - name: GOPATH
          value: /projects:/home/user/go
        - name: GOCACHE
          value: /tmp/.cache
      memoryLimit: 2Gi
      mountSources: true
